import {Dimensions, StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    width: '100%',
    height: Dimensions.get('window').height,
    backgroundColor: '#fff',
  },
  timerContainer: {
    paddingVertical: '10%',
  },
  toolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
    marginTop: 10,
    backgroundColor: '#fff',
  },
  toolbarIcon: {
    backgroundColor: '#EBFFFE',
    padding: 10,
    borderRadius: 50,
  },
  toolbarHeading: {
    fontSize: 20,
    color: '#00818E',
    alignSelf: 'center',
  },
  cell: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: '10%',
    marginVertical: 20,
  },
  cellHeading: {fontSize: 25, color: '#00818E'},
  textValue: {fontSize: 25, color: '#00818E'},
  inputContainer: {
    flexDirection: 'row',
    width: '40%',
    padding: 20,
    borderBottomStartRadius: 20,
    borderBottomEndRadius: 20,
    borderTopStartRadius: 20,
    backgroundColor: '#fff',
    shadowColor: '#FF6B6B',
    shadowOffset: {width: 0, height: 4},
    shadowOpacity: 1,
    shadowRadius: 5,
    elevation: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  start: {
    width: '30%',
    backgroundColor: 'red',
    backgroundColor: '#00818E',
    alignSelf: 'center',

    //   marginHorizontal: '30%',
    // marginBottom:20,
  },
  startButton: {
    fontSize: 20,
    color: '#fff',
    padding: 20,
    alignSelf: 'center',
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#0006',
  },
  modalView: {
    width: '80%',
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#00818E',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 20,
    color: '#00818E',
  },
  modalButton: {
    width: '50%',
    backgroundColor: '#00818E',
    borderRadius: 20,
    padding: 10,
    elevation: 2,
    marginBottom: 10,
  },
  buttonText: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 16,
  },
  input: {
    backgroundColor: '#EBFFFE',
    width: '20%',
    borderColor: '#00818E',
    borderWidth: 1,
  },
  okButtonText: {
    backgroundColor: '#00818E',
    color: '#fff',
    paddingHorizontal: 25,
    paddingVertical: 10,
    marginTop:10,
  },
});

export default styles;
